version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_password
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_RANDOM_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    command: ["gunicorn", "ecommerce.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=ecommerce_user
      - MYSQL_PASSWORD=ecommerce_password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular
    volumes:
      - ./frontend:/app
    ports:
      - "4200:80"

volumes:
  db_data:
