# Generated by Django 4.2.7 on 2024-04-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
    ]
